import type { Scenario } from './types'

export const SCENARIOS: Scenario[] = [
  {
    _name: 'Brand-new healthy laptop',
    _expected_action: 'REDEPLOY',
    _expected_risk_score: 0.017,
    asset_id: 'TEST-001',
    device_type: 'Laptop',
    brand: 'Dell',
    department: 'Engineering',
    region: 'North America',
    usage_type: 'Standard',
    os: 'Windows 11',
    age_in_months: 6,
    model_year: 2026,
    battery_health_percent: 98.0,
    battery_cycles: 40,
    smart_sectors_reallocated: 0,
    thermal_events_count: 0,
    overheating_issues: 'False',
    daily_usage_hours: 8.0,
    performance_rating: 5,
    total_incidents: 0,
    critical_incidents: 0,
    high_incidents: 0,
    medium_incidents: 0,
    low_incidents: 0,
    avg_resolution_time_hours: 24.0,
    data_completeness: 1.0,
  },
  {
    _name: 'Young asset, minor wear',
    _expected_action: 'REDEPLOY',
    _expected_risk_score: 0.115,
    asset_id: 'TEST-002',
    device_type: 'Laptop',
    brand: 'Dell',
    department: 'Engineering',
    region: 'North America',
    usage_type: 'Standard',
    os: 'Windows 11',
    age_in_months: 18,
    model_year: 2024,
    battery_health_percent: 88.0,
    battery_cycles: 180,
    smart_sectors_reallocated: 5,
    thermal_events_count: 2,
    overheating_issues: 'False',
    daily_usage_hours: 8.0,
    performance_rating: 4,
    total_incidents: 3,
    critical_incidents: 0,
    high_incidents: 0,
    medium_incidents: 0,
    low_incidents: 3,
    avg_resolution_time_hours: 24.0,
    data_completeness: 1.0,
  },
  {
    _name: 'Mid-life, average wear',
    _expected_action: 'RESALE',
    _expected_risk_score: 0.304,
    asset_id: 'TEST-003',
    device_type: 'Laptop',
    brand: 'Dell',
    department: 'Engineering',
    region: 'North America',
    usage_type: 'Standard',
    os: 'Windows 11',
    age_in_months: 36,
    model_year: 2023,
    battery_health_percent: 74.0,
    battery_cycles: 400,
    smart_sectors_reallocated: 28,
    thermal_events_count: 7,
    overheating_issues: 'False',
    daily_usage_hours: 8.0,
    performance_rating: 3,
    total_incidents: 8,
    critical_incidents: 1,
    high_incidents: 1,
    medium_incidents: 2,
    low_incidents: 4,
    avg_resolution_time_hours: 24.0,
    data_completeness: 1.0,
  },
  {
    _name: 'Overheating server, aging',
    _expected_action: 'REFURBISH',
    _expected_risk_score: 0.584,
    asset_id: 'TEST-004',
    device_type: 'Server',
    brand: 'HPE',
    department: 'Engineering',
    region: 'North America',
    usage_type: 'Standard',
    os: 'Linux',
    age_in_months: 50,
    model_year: 2021,
    battery_health_percent: 60.0,
    battery_cycles: 600,
    smart_sectors_reallocated: 60,
    thermal_events_count: 35,
    overheating_issues: 'True',
    daily_usage_hours: 8.0,
    performance_rating: 2,
    total_incidents: 12,
    critical_incidents: 2,
    high_incidents: 2,
    medium_incidents: 3,
    low_incidents: 5,
    avg_resolution_time_hours: 24.0,
    data_completeness: 1.0,
  },
  {
    _name: 'End-of-life, all signals maxed',
    _expected_action: 'RECYCLE',
    _expected_risk_score: 0.932,
    asset_id: 'TEST-005',
    device_type: 'Desktop',
    brand: 'Lenovo',
    department: 'Engineering',
    region: 'North America',
    usage_type: 'Standard',
    os: 'Windows 11',
    age_in_months: 72,
    model_year: 2019,
    battery_health_percent: 20.0,
    battery_cycles: 900,
    smart_sectors_reallocated: 95,
    thermal_events_count: 48,
    overheating_issues: 'True',
    daily_usage_hours: 8.0,
    performance_rating: 1,
    total_incidents: 20,
    critical_incidents: 4,
    high_incidents: 4,
    medium_incidents: 6,
    low_incidents: 6,
    avg_resolution_time_hours: 24.0,
    data_completeness: 1.0,
  },
  {
    _name: 'Borderline medium/high (~0.54)',
    _expected_action: 'RESALE',
    _expected_risk_score: 0.387,
    asset_id: 'TEST-006',
    device_type: 'Laptop',
    brand: 'Dell',
    department: 'Engineering',
    region: 'North America',
    usage_type: 'Standard',
    os: 'Windows 11',
    age_in_months: 40,
    model_year: 2022,
    battery_health_percent: 65.0,
    battery_cycles: 450,
    smart_sectors_reallocated: 35,
    thermal_events_count: 14,
    overheating_issues: 'False',
    daily_usage_hours: 8.0,
    performance_rating: 3,
    total_incidents: 9,
    critical_incidents: 1,
    high_incidents: 1,
    medium_incidents: 2,
    low_incidents: 5,
    avg_resolution_time_hours: 24.0,
    data_completeness: 1.0,
  },
  {
    _name: 'Borderline low/medium (~0.35)',
    _expected_action: 'REDEPLOY',
    _expected_risk_score: 0.174,
    asset_id: 'TEST-007',
    device_type: 'Laptop',
    brand: 'Dell',
    department: 'Engineering',
    region: 'North America',
    usage_type: 'Standard',
    os: 'Windows 11',
    age_in_months: 20,
    model_year: 2024,
    battery_health_percent: 83.0,
    battery_cycles: 220,
    smart_sectors_reallocated: 12,
    thermal_events_count: 4,
    overheating_issues: 'False',
    daily_usage_hours: 8.0,
    performance_rating: 4,
    total_incidents: 5,
    critical_incidents: 0,
    high_incidents: 1,
    medium_incidents: 1,
    low_incidents: 3,
    avg_resolution_time_hours: 24.0,
    data_completeness: 1.0,
  },
  {
    _name: 'Old but well-maintained',
    _expected_action: 'REDEPLOY',
    _expected_risk_score: 0.231,
    asset_id: 'TEST-008',
    device_type: 'Laptop',
    brand: 'Dell',
    department: 'Engineering',
    region: 'North America',
    usage_type: 'Standard',
    os: 'Windows 11',
    age_in_months: 60,
    model_year: 2020,
    battery_health_percent: 85.0,
    battery_cycles: 700,
    smart_sectors_reallocated: 8,
    thermal_events_count: 3,
    overheating_issues: 'False',
    daily_usage_hours: 8.0,
    performance_rating: 4,
    total_incidents: 4,
    critical_incidents: 0,
    high_incidents: 0,
    medium_incidents: 1,
    low_incidents: 3,
    avg_resolution_time_hours: 24.0,
    data_completeness: 1.0,
  },
  {
    _name: 'Partial telemetry (completeness=0.45)',
    _expected_action: 'REDEPLOY',
    _expected_risk_score: 0.231,
    asset_id: 'TEST-009',
    device_type: 'Laptop',
    brand: 'Dell',
    department: 'Engineering',
    region: 'North America',
    usage_type: 'Standard',
    os: 'Windows 11',
    age_in_months: 30,
    model_year: 2023,
    battery_health_percent: 79.0,
    battery_cycles: 310,
    smart_sectors_reallocated: 18,
    thermal_events_count: 5,
    overheating_issues: 'False',
    daily_usage_hours: 8.0,
    performance_rating: 3,
    total_incidents: 6,
    critical_incidents: 1,
    high_incidents: 1,
    medium_incidents: 1,
    low_incidents: 3,
    avg_resolution_time_hours: 24.0,
    data_completeness: 0.45,
  },
  {
    _name: 'High incidents, young device',
    _expected_action: 'RESALE',
    _expected_risk_score: 0.362,
    asset_id: 'TEST-010',
    device_type: 'Laptop',
    brand: 'Dell',
    department: 'Engineering',
    region: 'North America',
    usage_type: 'Standard',
    os: 'Windows 11',
    age_in_months: 14,
    model_year: 2025,
    battery_health_percent: 90.0,
    battery_cycles: 150,
    smart_sectors_reallocated: 55,
    thermal_events_count: 12,
    overheating_issues: 'True',
    daily_usage_hours: 8.0,
    performance_rating: 2,
    total_incidents: 15,
    critical_incidents: 3,
    high_incidents: 3,
    medium_incidents: 4,
    low_incidents: 5,
    avg_resolution_time_hours: 24.0,
    data_completeness: 1.0,
  },
]
